services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: courseonlinedb
      POSTGRES_USER: midbenke
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/courseonlinedb
      SPRING_DATASOURCE_USERNAME: midbenke
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  db-data:
